### DISCUSSION TITLE
Awesome stuff folks - great first release

### DISCUSSION THREAD

**Discussion by martinleach** [grit42/grit#1] [Show and tell]
I modified the .yaml  to docker pull and setup on a macos running M3 Max
basically - just removed the platform lineitem

i removed:
platform: linux/amd64 

changed:
volumes:
  - ./postgres-data:/var/lib/postgresql/data
  
to 

volumes:
  - postgres_data:/var/lib/postgresql/data

and added
volumes:
  postgres_data:

at bottom of file

seems to be running well
i would recommend adding some 'dummy' data in there to populate it original - at least one of everything
might be an option on the build 

I blundered around setting up a compound as I didn't RTFM
still struggling to load a dataset but resisting the urge to RTFM

based on the admin interface, as you have to setup types then metadata, models then assays - it seemed non-counterintuitive as the 'last thing' on the UI (types) is the first thing you have to setup - i would re-order the listing of these on the UI. Think about the order on the UI as the order someone needs to set things up.

great first release everyone - you certainly deserve several pints of beer, some peanuts and a brand spanking new towel!!! 

so long and thanks for all the grit

Martin Leach

-----

```yaml
version: "3.8"

services:
  db:
    image: grit42com/pgrdkit:16.3-2024.03.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=grit
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Remove platform to allow native ARM64 execution on M3 Max

  app:
    image: grit42com/grit:0.1.1
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=grit
      - POSTGRES_PASSWORD=password
      - GRIT_DATABASE=grit
      - SECRET_KEY_BASE=secretkeybase
    restart: unless-stopped
    # Also no platform override

volumes:
  postgres_data:
```
